package `in`.xroden.flockr.core.validation

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/** Invite codes are generated by the database, so the app must accept exactly what it generates. */
class ValidatorsTest {

    @Test
    fun `a generated code is accepted in any case and with stray spaces`() {
        assertEquals("B4LY7Z7Z", Validators.validateInviteCode(" b4ly7z7z ").getOrThrow())
    }

    @Test
    fun `codes of the wrong length or with look-alike characters are refused`() {
        assertTrue(Validators.validateInviteCode("B4LY7Z").isFailure)
        assertTrue(Validators.validateInviteCode("B4LY7Z7Z9").isFailure)
        assertTrue(Validators.validateInviteCode("B4LY7Z7O").isFailure)
        assertTrue(Validators.validateInviteCode("B4LY7Z71").isFailure)
    }
}
